/*16. Crie uma lógica que preencha um vetor de 20 posições com números aleatórios
(entre 0 e 99) gerados pelo computador. Logo em seguida, mostre os números gerados e
depois coloque o vetor em ordem crescente, mostrando no final os valores ordenados.*/

const arrayLength20 = [];

for(i = 0; arrayLength20.length < 20; i++){
    let randomNumber = parseInt(Math.random() * 100);
    arrayLength20.push(randomNumber);
}

console.log(`The numbers generated by the computer were: ${arrayLength20}`);

//Mostrar o array na ordem crescente
const arrayInAscendingOrder = [...arrayLength20].sort((a, b) => a - b); //[...arrayLength20]: Usa o operador de espalhamento (spread operator) para criar uma cópia do array arrayLength20, evitando alterar o array original.
//.sort((a, b) => a - b): Ordena a cópia do array em ordem crescente.
console.log(`The numbers generated by the computer in ascending order: ${arrayInAscendingOrder}`);
